. $PSScriptRoot\Soap\Block-Traffic.ps1
. $PSScriptRoot\Soap\Clear-AuditPolicy.ps1
. $PSScriptRoot\Soap\Disable-Firewall.ps1
. $PSScriptRoot\Soap\Disable-IPv6.ps1
. $PSScriptRoot\Soap\Edit-Firewall.ps1
. $PSScriptRoot\Soap\Edit-Module.ps1
. $PSScriptRoot\Soap\Enable-IPv6.ps1
. $PSScriptRoot\Soap\Enable-WinRm.ps1
. $PSScriptRoot\Soap\Find-IpAddressInWindowsEventLog.ps1
. $PSScriptRoot\Soap\Get-AuditPolicy.ps1
. $PSScriptRoot\Soap\Get-AutoRuns.ps1
. $PSScriptRoot\Soap\Get-DiskSpace.ps1
. $PSScriptRoot\Soap\Get-DomainAdministrator.ps1
. $PSScriptRoot\Soap\Get-LocalAdministrator.ps1
. $PSScriptRoot\Soap\Get-ProcessByNetworkConnection.ps1
. $PSScriptRoot\Soap\Get-WinEventDns.ps1
. $PSScriptRoot\Soap\Get-WinEventFirewall.ps1
. $PSScriptRoot\Soap\Get-WinEventLogon.ps1
. $PSScriptRoot\Soap\Get-WinEventPowerShell.ps1
. $PSScriptRoot\Soap\Get-WinEventProcessCreation.ps1
. $PSScriptRoot\Soap\Get-WinEventService.ps1
. $PSScriptRoot\Soap\Get-WinEventUsb.ps1
. $PSScriptRoot\Soap\Get-WinEventWindowsDefender.ps1
. $PSScriptRoot\Soap\Get-WinRmClient.ps1
. $PSScriptRoot\Soap\Get-WordWheelQuery.ps1
. $PSScriptRoot\Soap\Read-WinEvent.ps1
. $PSScriptRoot\Soap\Set-AuditPolicy.ps1
. $PSScriptRoot\Soap\Start-AdAccountAudit.ps1
. $PSScriptRoot\Soap\Start-Eradication.ps1
. $PSScriptRoot\Soap\Start-Heartbeat.ps1