## SOAP
SOAP is a PowerShell module for security operations and automation. See below for the list of functions either in development or available now: 
- [ ] Start-LogEnrichment
- [x] Start-ProcessReaper
- [ ] Invoke-APT1 
- [x] Invoke-AdScrub
- [x] Invoke-SystemAudit
- [ ] Get-LogonRights
- [ ] Get-FilePermissions
- [ ] Get-IntegrityLevels 
- [x] Get-LocalAdmins
- [x] Get-OpenPorts
- [x] Get-Shares
- [x] Get-WirelessComputers
- [ ] Get-DomainAdmins
- [ ] Get-Privileges
- [x] Invoke-CyberEffect
- [x] Start-RollingReboot
- [ ] Start-Scareware
- [x] Get-SuspiciousFile 
- [ ] Start-Panic
- [x] Stop-EvilProcess
- [x] Block-TrafficToIpAddress
- [x] Unblock-TrafficToIpAddress
- [x] Enable-WinRm
- [x] Get-Asset
- [ ] Get-DiskSpace
- [ ] Move-Logs
- [ ] Remove-Program
- [x] Get-IpAddressFromFirewallLog  
